// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// This file is generated by Apache Fory compiler.

package at.ac.uibk.dps.cirrina.fory.exchange;

import org.apache.fory.Fory;
import org.apache.fory.ThreadSafeFory;
import org.apache.fory.pool.SimpleForyPool;

public class ExchangeForyRegistration {

    static ThreadSafeFory getFory() {
        return Holder.FORY;
    }

    private static ThreadSafeFory createFory() {
        ThreadSafeFory fory = new SimpleForyPool(c -> Fory.builder().withXlang(true).withRefTracking(true).build());
        fory.registerCallback(f -> register(f));
        return fory;
    }

    private static class Holder {
        private static final ThreadSafeFory FORY = createFory();
    }

    public static void register(Fory fory) {
        org.apache.fory.resolver.TypeResolver resolver = fory.getTypeResolver();
        resolver.register(ForyDescriptorProtos.EventChannel.class, 1966690358L);
        resolver.registerUnion(ForyDescriptorProtos.Value.class, 1735978127L, new org.apache.fory.serializer.UnionSerializer(fory, ForyDescriptorProtos.Value.class));
        resolver.register(ForyDescriptorProtos.ContextVariable.class, 2542241118L);
        resolver.register(ForyDescriptorProtos.Event.class, 2591768396L);
    }
}
