// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// This file is generated by Apache Fory compiler.

package at.ac.uibk.dps.cirrina.fory.exchange;

import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.apache.fory.annotation.ForyField;
import org.apache.fory.annotation.Ref;
import org.apache.fory.annotation.Uint64Type;
import org.apache.fory.config.LongEncoding;
import org.apache.fory.type.Types;
import org.apache.fory.type.union.Union;

public final class ForyDescriptorProtos {

    private ForyDescriptorProtos() {
        // Prevent instantiation
    }

    public static enum EventChannel {
        INTERNAL,
        EXTERNAL,
        PERIPHERAL;
    }
    
    // Type ID 1735978127 is generated from at.ac.uibk.dps.cirrina.fory.exchange.Value
    public static final class Value extends Union {
        public enum ValueCase {
            INTEGER(1),
            FLOAT(2),
            LONG(3),
            DOUBLE(4),
            STRING(5),
            BOOL(6),
            BYTES(7),
            ARRAY(8),
            VALUE_LIST(9),
            VALUE_MAP(10);
            public final int id;
            ValueCase(int id) {
                this.id = id;
            }
        }
    
        private static int resolveTypeId(int caseId) {
            switch (caseId) {
                case 1:
                    return Types.VARINT32;
                case 2:
                    return Types.FLOAT32;
                case 3:
                    return Types.VARINT64;
                case 4:
                    return Types.FLOAT64;
                case 5:
                    return Types.STRING;
                case 6:
                    return Types.BOOL;
                case 7:
                    return Types.BINARY;
                case 8:
                    return Types.LIST;
                case 9:
                    return Types.LIST;
                case 10:
                    return Types.MAP;
                default:
                    throw new IllegalStateException("Unknown Value case id: " + caseId);
            }
        }
    
        private Value(int caseId, Object v) {
            super(caseId, v, resolveTypeId(caseId));
            if (v == null) {
                throw new NullPointerException();
            }
            getValueCase();
        }
    
        public static Value ofInteger(int v) {
            return new Value(ValueCase.INTEGER.id, v);
        }
    
        public static Value ofFloat(float v) {
            return new Value(ValueCase.FLOAT.id, v);
        }
    
        public static Value ofLong(long v) {
            return new Value(ValueCase.LONG.id, v);
        }
    
        public static Value ofDouble(double v) {
            return new Value(ValueCase.DOUBLE.id, v);
        }
    
        public static Value ofString(String v) {
            return new Value(ValueCase.STRING.id, v);
        }
    
        public static Value ofBool(boolean v) {
            return new Value(ValueCase.BOOL.id, v);
        }
    
        public static Value ofBytes(byte[] v) {
            return new Value(ValueCase.BYTES.id, v);
        }
    
        public static Value ofArray(List<@Ref(enable=false) Value> v) {
            return new Value(ValueCase.ARRAY.id, v);
        }
    
        public static Value ofValueList(List<@Ref(enable=false) Value> v) {
            return new Value(ValueCase.VALUE_LIST.id, v);
        }
    
        public static Value ofValueMap(Map<Value, @Ref(enable=false) Value> v) {
            return new Value(ValueCase.VALUE_MAP.id, v);
        }
    
        public ValueCase getValueCase() {
            switch (index) {
                case 1:
                    return ValueCase.INTEGER;
                case 2:
                    return ValueCase.FLOAT;
                case 3:
                    return ValueCase.LONG;
                case 4:
                    return ValueCase.DOUBLE;
                case 5:
                    return ValueCase.STRING;
                case 6:
                    return ValueCase.BOOL;
                case 7:
                    return ValueCase.BYTES;
                case 8:
                    return ValueCase.ARRAY;
                case 9:
                    return ValueCase.VALUE_LIST;
                case 10:
                    return ValueCase.VALUE_MAP;
                default:
                    throw new IllegalStateException("Unknown Value case id: " + index);
            }
        }
    
        public int getValueCaseId() {
            return index;
        }
    
        public boolean hasInteger() {
            return index == ValueCase.INTEGER.id;
        }
    
        public int getInteger() {
            if (index != ValueCase.INTEGER.id) {
                throw new IllegalStateException("Value is not INTEGER");
            }
            return (Integer) value;
        }
    
        public void setInteger(int v) {
            this.index = ValueCase.INTEGER.id;
            this.value = v;
            this.typeId = Types.VARINT32;
        }
    
        public boolean hasFloat() {
            return index == ValueCase.FLOAT.id;
        }
    
        public float getFloat() {
            if (index != ValueCase.FLOAT.id) {
                throw new IllegalStateException("Value is not FLOAT");
            }
            return (Float) value;
        }
    
        public void setFloat(float v) {
            this.index = ValueCase.FLOAT.id;
            this.value = v;
            this.typeId = Types.FLOAT32;
        }
    
        public boolean hasLong() {
            return index == ValueCase.LONG.id;
        }
    
        public long getLong() {
            if (index != ValueCase.LONG.id) {
                throw new IllegalStateException("Value is not LONG");
            }
            return (Long) value;
        }
    
        public void setLong(long v) {
            this.index = ValueCase.LONG.id;
            this.value = v;
            this.typeId = Types.VARINT64;
        }
    
        public boolean hasDouble() {
            return index == ValueCase.DOUBLE.id;
        }
    
        public double getDouble() {
            if (index != ValueCase.DOUBLE.id) {
                throw new IllegalStateException("Value is not DOUBLE");
            }
            return (Double) value;
        }
    
        public void setDouble(double v) {
            this.index = ValueCase.DOUBLE.id;
            this.value = v;
            this.typeId = Types.FLOAT64;
        }
    
        public boolean hasString() {
            return index == ValueCase.STRING.id;
        }
    
        public String getString() {
            if (index != ValueCase.STRING.id) {
                throw new IllegalStateException("Value is not STRING");
            }
            return (String) value;
        }
    
        public void setString(String v) {
            if (v == null) {
                throw new NullPointerException();
            }
            this.index = ValueCase.STRING.id;
            this.value = v;
            this.typeId = Types.STRING;
        }
    
        public boolean hasBool() {
            return index == ValueCase.BOOL.id;
        }
    
        public boolean getBool() {
            if (index != ValueCase.BOOL.id) {
                throw new IllegalStateException("Value is not BOOL");
            }
            return (Boolean) value;
        }
    
        public void setBool(boolean v) {
            this.index = ValueCase.BOOL.id;
            this.value = v;
            this.typeId = Types.BOOL;
        }
    
        public boolean hasBytes() {
            return index == ValueCase.BYTES.id;
        }
    
        public byte[] getBytes() {
            if (index != ValueCase.BYTES.id) {
                throw new IllegalStateException("Value is not BYTES");
            }
            return (byte[]) value;
        }
    
        public void setBytes(byte[] v) {
            if (v == null) {
                throw new NullPointerException();
            }
            this.index = ValueCase.BYTES.id;
            this.value = v;
            this.typeId = Types.BINARY;
        }
    
        public boolean hasArray() {
            return index == ValueCase.ARRAY.id;
        }
    
        public List<@Ref(enable=false) Value> getArray() {
            if (index != ValueCase.ARRAY.id) {
                throw new IllegalStateException("Value is not ARRAY");
            }
            return (List<@Ref(enable=false) Value>) value;
        }
    
        public void setArray(List<@Ref(enable=false) Value> v) {
            if (v == null) {
                throw new NullPointerException();
            }
            this.index = ValueCase.ARRAY.id;
            this.value = v;
            this.typeId = Types.LIST;
        }
    
        public boolean hasValueList() {
            return index == ValueCase.VALUE_LIST.id;
        }
    
        public List<@Ref(enable=false) Value> getValueList() {
            if (index != ValueCase.VALUE_LIST.id) {
                throw new IllegalStateException("Value is not VALUE_LIST");
            }
            return (List<@Ref(enable=false) Value>) value;
        }
    
        public void setValueList(List<@Ref(enable=false) Value> v) {
            if (v == null) {
                throw new NullPointerException();
            }
            this.index = ValueCase.VALUE_LIST.id;
            this.value = v;
            this.typeId = Types.LIST;
        }
    
        public boolean hasValueMap() {
            return index == ValueCase.VALUE_MAP.id;
        }
    
        public Map<Value, @Ref(enable=false) Value> getValueMap() {
            if (index != ValueCase.VALUE_MAP.id) {
                throw new IllegalStateException("Value is not VALUE_MAP");
            }
            return (Map<Value, @Ref(enable=false) Value>) value;
        }
    
        public void setValueMap(Map<Value, @Ref(enable=false) Value> v) {
            if (v == null) {
                throw new NullPointerException();
            }
            this.index = ValueCase.VALUE_MAP.id;
            this.value = v;
            this.typeId = Types.MAP;
        }
    
        @Override
        public boolean equals(Object o) {
            if (this == o) {
                return true;
            }
            if (!(o instanceof Value)) {
                return false;
            }
            Value that = (Value) o;
            return index == that.index && Objects.equals(value, that.value);
        }
    
        @Override
        public int hashCode() {
            return Objects.hash(index, value);
        }
    
        public byte[] toBytes() {
            return ExchangeForyRegistration.getFory().serialize(this);
        }
        
        public static Value fromBytes(byte[] bytes) {
            return ExchangeForyRegistration.getFory().deserialize(bytes, Value.class);
        }
        
    }
    
        // Type ID 2542241118 is generated from at.ac.uibk.dps.cirrina.fory.exchange.ContextVariable
    public static class ContextVariable {
        @ForyField(id = 1)
        private String name;
        
        @ForyField(id = 2, nullable = true)
        private Value value;
        
    
        public ContextVariable() {
        }
    
        public String getName() {
            return name;
        }
        
        public void setName(String name) {
            this.name = name;
        }
        
        public Value getValue() {
            return value;
        }
        
        public void setValue(Value value) {
            this.value = value;
        }
        
        public byte[] toBytes() {
            return ExchangeForyRegistration.getFory().serialize(this);
        }
        
        public static ContextVariable fromBytes(byte[] bytes) {
            return ExchangeForyRegistration.getFory().deserialize(bytes, ContextVariable.class);
        }
        
        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append("ContextVariable(");
            sb.append("name=");
            sb.append(name);
            sb.append(", ");
            sb.append("value=");
            sb.append(value);
            sb.append(")");
            return sb.toString();
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            ContextVariable that = (ContextVariable) o;
            return Objects.equals(name, that.name)
                && Objects.equals(value, that.value);
        }
        
        @Override
        public int hashCode() {
            return Objects.hash(name, value);
        }
        
    }
    
        // Type ID 2591768396 is generated from at.ac.uibk.dps.cirrina.fory.exchange.Event
    public static class Event {
        @ForyField(id = 1)
        private String topic;
        
        @ForyField(id = 2)
        private EventChannel channel;
        
        @ForyField(id = 3)
        private List<@Ref(enable=false) ContextVariable> data;
        
        @ForyField(id = 4)
        private String target;
        
        @ForyField(id = 5)
        private String source;
        
        @ForyField(id = 6)
        private String id;
        
        @ForyField(id = 7)
        @Uint64Type(encoding = LongEncoding.FIXED)
        private long emittedTime;
        
    
        public Event() {
        }
    
        public String getTopic() {
            return topic;
        }
        
        public void setTopic(String topic) {
            this.topic = topic;
        }
        
        public EventChannel getChannel() {
            return channel;
        }
        
        public void setChannel(EventChannel channel) {
            this.channel = channel;
        }
        
        public List<@Ref(enable=false) ContextVariable> getData() {
            return data;
        }
        
        public void setData(List<@Ref(enable=false) ContextVariable> data) {
            this.data = data;
        }
        
        public String getTarget() {
            return target;
        }
        
        public void setTarget(String target) {
            this.target = target;
        }
        
        public String getSource() {
            return source;
        }
        
        public void setSource(String source) {
            this.source = source;
        }
        
        public String getId() {
            return id;
        }
        
        public void setId(String id) {
            this.id = id;
        }
        
        public long getEmittedTime() {
            return emittedTime;
        }
        
        public void setEmittedTime(long emittedTime) {
            this.emittedTime = emittedTime;
        }
        
        public byte[] toBytes() {
            return ExchangeForyRegistration.getFory().serialize(this);
        }
        
        public static Event fromBytes(byte[] bytes) {
            return ExchangeForyRegistration.getFory().deserialize(bytes, Event.class);
        }
        
        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append("Event(");
            sb.append("topic=");
            sb.append(topic);
            sb.append(", ");
            sb.append("channel=");
            sb.append(channel);
            sb.append(", ");
            sb.append("data=");
            sb.append(data);
            sb.append(", ");
            sb.append("target=");
            sb.append(target);
            sb.append(", ");
            sb.append("source=");
            sb.append(source);
            sb.append(", ");
            sb.append("id=");
            sb.append(id);
            sb.append(", ");
            sb.append("emittedTime=");
            sb.append(emittedTime);
            sb.append(")");
            return sb.toString();
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Event that = (Event) o;
            return Objects.equals(topic, that.topic)
                && Objects.equals(channel, that.channel)
                && Objects.equals(data, that.data)
                && Objects.equals(target, that.target)
                && Objects.equals(source, that.source)
                && Objects.equals(id, that.id)
                && Objects.equals(emittedTime, that.emittedTime);
        }
        
        @Override
        public int hashCode() {
            return Objects.hash(topic, channel, data, target, source, id, emittedTime);
        }
        
    }
    
}
